default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  host: localhost
  timeout: 5000
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>
  variables:
    statement_timeout: <%= ENV["DB_STATEMENT_TIMEOUT"] || 120_000 %>

development:
  <<: *default
  database: code_challenge_rails_development

test:
  <<: *default
  database: code_challenge_rails_test

staging:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>

production:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>
